
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER1
 */
public class Actualizar extends javax.swing.JFrame {
public static String nombreCancion;
/**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
        Fildcombo();
       
        //if(actnombre.isSelected()){nnombre.setVisible(false);} else nnombre.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actnombre2 = new javax.swing.JToggleButton();
        nnombre2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nnombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        actnombre = new javax.swing.JToggleButton();
        actartista = new javax.swing.JToggleButton();
        nartista = new javax.swing.JTextField();
        nimg = new javax.swing.JTextField();
        actanio = new javax.swing.JToggleButton();
        actlink = new javax.swing.JToggleButton();
        nlink = new javax.swing.JTextField();
        nanio = new javax.swing.JTextField();
        actimg = new javax.swing.JToggleButton();
        ntipo = new javax.swing.JComboBox();
        ngenero = new javax.swing.JComboBox();
        actgenero = new javax.swing.JToggleButton();
        acttipo = new javax.swing.JToggleButton();

        actnombre2.setText("Actualizar Nombre");
        actnombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actnombre2ActionPerformed(evt);
            }
        });

        nnombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nnombre2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Actualizar canción");

        nnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nnombreActionPerformed(evt);
            }
        });

        jButton1.setText("Aplicar cambios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Menú");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        actnombre.setText("Actualizar Nombre");
        actnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actnombreActionPerformed(evt);
            }
        });

        actartista.setText("Actualizar Artista");
        actartista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actartistaActionPerformed(evt);
            }
        });

        nartista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nartistaActionPerformed(evt);
            }
        });

        nimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimgActionPerformed(evt);
            }
        });

        actanio.setText("Actualizar Año");
        actanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actanioActionPerformed(evt);
            }
        });

        actlink.setText("Actualizar link");
        actlink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actlinkActionPerformed(evt);
            }
        });

        nlink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nlinkActionPerformed(evt);
            }
        });

        nanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nanioActionPerformed(evt);
            }
        });

        actimg.setText("Actualizar Imagen");
        actimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actimgActionPerformed(evt);
            }
        });

        ntipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Album", "Single" }));
        ntipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntipoActionPerformed(evt);
            }
        });

        ngenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dance", "Jazz", "Rap", "Hip-Hop" }));
        ngenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngeneroActionPerformed(evt);
            }
        });

        actgenero.setText("Actualizar Género");
        actgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actgeneroActionPerformed(evt);
            }
        });

        acttipo.setText("Actualizar Tipo");
        acttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acttipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(actimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(actgenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(acttipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nimg, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ngenero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ntipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(actlink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(actanio, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nlink, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nanio, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(actartista)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nartista, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(actnombre)
                                    .addGap(29, 29, 29)
                                    .addComponent(nnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(jButton1)
                            .addGap(68, 68, 68)
                            .addComponent(jButton2))))
                .addGap(22, 47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actnombre)
                    .addComponent(nnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actartista)
                    .addComponent(nartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actanio)
                    .addComponent(nanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actlink)
                    .addComponent(nlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actimg)
                    .addComponent(nimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actgenero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ntipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acttipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Fildcombo(){
        
        try{
            Connection con = Conection.getConexion();
            String sql = "Select distinct nombre from generocancion order by nombre";
            PreparedStatement psmt = con.prepareStatement(sql);
            ResultSet rs;
            rs = psmt.executeQuery();
            
            while(rs.next()){
            String generito=rs.getString("Nombre");
            ngenero.addItem(generito);
            }
         } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         PaginaAdmin newFrame = new PaginaAdmin();
            newFrame.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void actnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actnombreActionPerformed
        // TODO add your handling code here:
        
        if(actnombre.isSelected()){nnombre.setVisible(false);} else nnombre.setVisible(true);
    }//GEN-LAST:event_actnombreActionPerformed

    private void nnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nnombreActionPerformed

    private void actartistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actartistaActionPerformed
if(actartista.isSelected()){nartista.setVisible(false);} else nartista.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_actartistaActionPerformed

    private void nartistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nartistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nartistaActionPerformed

    private void actnombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actnombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actnombre2ActionPerformed

    private void nnombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nnombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nnombre2ActionPerformed

    private void nimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimgActionPerformed

    private void actanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actanioActionPerformed
if(actanio.isSelected()){nanio.setVisible(false);} else nanio.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_actanioActionPerformed

    private void actlinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actlinkActionPerformed
if(actlink.isSelected()){nlink.setVisible(false);} else nlink.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_actlinkActionPerformed

    private void nlinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nlinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nlinkActionPerformed

    private void nanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nanioActionPerformed

    private void actimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actimgActionPerformed
if(actimg.isSelected()){nimg.setVisible(false);} else nimg.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_actimgActionPerformed

    private void ntipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntipoActionPerformed

    private void ngeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngeneroActionPerformed

    private void actgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actgeneroActionPerformed
if(actgenero.isSelected()){ngenero.setVisible(false);} else ngenero.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_actgeneroActionPerformed

    private void acttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acttipoActionPerformed
if(acttipo.isSelected()){ntipo.setVisible(false);} else ntipo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_acttipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //String tempNombre = nombreCancion.getText();
        if(!actnombre.isSelected()){
            try{

                Connection con = Conection.getConexion();
                String query = "call UPDcancion('"+nnombre.getText()+"', "+Visualizar.idcancion+");";

                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();

                System.out.println("sql success nnom");
            } catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
        }
        if(!actartista.isSelected()){
            try{

                Connection con = Conection.getConexion();
                String query = "call UPDartista('"+nartista.getText()+"', "+Visualizar.idartista+");";

                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();

                System.out.println("sql success nart");
            } catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
        }
        if(!actanio.isSelected()){
            try{

                Connection con = Conection.getConexion();
                String query = "call UPDanio('"+nanio.getText()+"', "+Visualizar.idTGC+");";

                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();

                System.out.println("sql success nanio");
            } catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
        }
        
        if(!actlink.isSelected()){
            try{

                Connection con = Conection.getConexion();
                String query = "call UPDlink('"+nlink.getText()+"', "+Visualizar.idcancion+");";

                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();

                System.out.println("sql success nli");
            } catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
        }
        
        if(!actimg.isSelected()){
            try{

                Connection con = Conection.getConexion();
                String query = "call UPDimg('"+nimg.getText()+"', "+Visualizar.idTGC+");";

                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();

                System.out.println("sql success nimg");
            } catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
        }
        
        if(!actgenero.isSelected()){
            try{
                String gener=String.valueOf(ngenero.getSelectedItem());
                Connection con = Conection.getConexion();
                String query = "call UPDgenero('"+gener+"', "+Visualizar.idgenero+");";

                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();

                System.out.println("sql success ngen");
            } catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
        }
        
        if(!acttipo.isSelected()){
            try{
                String tip=String.valueOf(ntipo.getSelectedItem());
                Connection con = Conection.getConexion();
                String query = "call UPDtipo('"+tip+"', "+Visualizar.idTGC+");";

                PreparedStatement psmt = con.prepareStatement(query);
                ResultSet rs;
                rs = psmt.executeQuery();

                System.out.println("sql success ntip");
            } catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton actanio;
    private javax.swing.JToggleButton actartista;
    private javax.swing.JToggleButton actgenero;
    private javax.swing.JToggleButton actimg;
    private javax.swing.JToggleButton actlink;
    private javax.swing.JToggleButton actnombre;
    private javax.swing.JToggleButton actnombre2;
    private javax.swing.JToggleButton acttipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nanio;
    private javax.swing.JTextField nartista;
    private javax.swing.JComboBox ngenero;
    private javax.swing.JTextField nimg;
    private javax.swing.JTextField nlink;
    private javax.swing.JTextField nnombre;
    private javax.swing.JTextField nnombre2;
    private javax.swing.JComboBox ntipo;
    // End of variables declaration//GEN-END:variables
}
