

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER1
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    public String usuarioNombre ="";
    
    public static ImageIcon format = null;
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        text_buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buscar_bot = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        tuNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomRecom1 = new javax.swing.JLabel();
        nomRecom2 = new javax.swing.JLabel();
        nomRecom3 = new javax.swing.JLabel();
        nomPop1 = new javax.swing.JLabel();
        nomPop2 = new javax.swing.JLabel();
        nomPop3 = new javax.swing.JLabel();
        recom3 = new javax.swing.JLabel();
        pop3 = new javax.swing.JLabel();
        recom2 = new javax.swing.JLabel();
        recom1 = new javax.swing.JLabel();
        pop1 = new javax.swing.JLabel();
        pop2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 153, 153));
        setName("Principal"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Filtrar busqueda: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Genero", "Cancion", "Artista" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Buscar:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 70, 14));
        getContentPane().add(text_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GUM Music");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 270, 40));

        buscar_bot.setText("Buscar");
        buscar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_botActionPerformed(evt);
            }
        });
        getContentPane().add(buscar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jButton8.setText("Salir");
        jButton8.setAlignmentX(10.0F);
        jButton8.setAlignmentY(40.0F);
        jButton8.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 70, 20));

        tuNombre.setText("Bienvenido:");
        getContentPane().add(tuNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setText("Recomendaciones");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel5.setText("Mejor calificados");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        nomRecom1.setText("text_c1");
        getContentPane().add(nomRecom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        nomRecom2.setText("text_c2");
        getContentPane().add(nomRecom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        nomRecom3.setText("text_c3");
        getContentPane().add(nomRecom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        nomPop1.setText("jLabel6");
        getContentPane().add(nomPop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        nomPop2.setText("jLabel6");
        getContentPane().add(nomPop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        nomPop3.setText("jLabel7");
        getContentPane().add(nomPop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        recom3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine_DragonsPequeña.jpg"))); // NOI18N
        getContentPane().add(recom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 120, 110));

        pop3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine_DragonsPequeña.jpg"))); // NOI18N
        getContentPane().add(pop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 120, 110));

        recom2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine_DragonsPequeña.jpg"))); // NOI18N
        getContentPane().add(recom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 110));

        recom1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine_DragonsPequeña.jpg"))); // NOI18N
        getContentPane().add(recom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 120, 110));

        pop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine_DragonsPequeña.jpg"))); // NOI18N
        getContentPane().add(pop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 120, 110));

        pop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine_DragonsPequeña.jpg"))); // NOI18N
        getContentPane().add(pop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 120, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void recomendaciones()
    {
        try{
              
           Connection con = Conection.getConexion();
            String query = "SELECT c.Nombre, t.imagen FROM tipogrupocanciones t JOIN cancion c ON c.fkidtipoGrupoCanciones = t.idtipoGrupoCanciones ORDER BY c.Calificacion ASC ";
            PreparedStatement psmt = con.prepareStatement(query);
            ResultSet rs;
            rs = psmt.executeQuery();
            
            String[] nomCancion = new String[3];
            ArrayList<byte[]> images = new ArrayList<byte[]>();
            for(int i = 0; i < 3; i++)
            {
               if(rs.next())
                {
                    nomCancion[i] = rs.getString("c.Nombre");
                    images.add(rs.getBytes("t.imagen"));
                }
            }
            
            nomRecom1.setText(nomCancion[0]);
            nomRecom2.setText(nomCancion[1]);
            nomRecom3.setText(nomCancion[2]);
            
            format = new ImageIcon(images.get(0));
            recom1.setIcon(format);
            
            format = new ImageIcon(images.get(1));
            recom2.setIcon(format);
            
            format = new ImageIcon(images.get(2));
            recom3.setIcon(format);
            
        }
     catch (SQLException ex){
            System.out.println(ex.getMessage());
            System.out.println("No existen valores");
        } 
    }
    
    public static void populares(){
        try{
              
           Connection con = Conection.getConexion();
            String query = "SELECT c.Nombre, t.imagen FROM tipogrupocanciones t JOIN cancion c ON c.fkidtipoGrupoCanciones = t.idtipoGrupoCanciones ORDER BY c.Calificacion DESC ";
            PreparedStatement psmt = con.prepareStatement(query);
            ResultSet rs;
            rs = psmt.executeQuery();
            
            String[] nomCancion = new String[3];
            ArrayList<byte[]> images = new ArrayList<byte[]>();
            for(int i = 0; i < 3; i++)
            {
               if(rs.next())
                {
                    nomCancion[i] = rs.getString("c.Nombre");
                    images.add(rs.getBytes("t.imagen"));
                }
            }
            
            nomPop1.setText(nomCancion[0]);
            nomPop2.setText(nomCancion[1]);
            nomPop3.setText(nomCancion[2]);
            
            format = new ImageIcon(images.get(0));
            pop1.setIcon(format);
            
            format = new ImageIcon(images.get(1));
            pop2.setIcon(format);
            
            format = new ImageIcon(images.get(2));
            pop3.setIcon(format);
            
        }
     catch (SQLException ex){
            System.out.println(ex.getMessage());
            System.out.println("No existen valores");
        } 
     
        
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
         
      
        InicioSesion newFrame = new InicioSesion ();
            newFrame.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void buscar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_botActionPerformed
        // TODO add your handling code here:
         String combo =String.valueOf( jComboBox1.getSelectedItem());
         String palabraBusqueda = text_buscar.getText();
         
        Buscar newFrame = new Buscar ();
            newFrame.setVisible(true);
            this.dispose();
            
        Buscar.palabraBusqueda = palabraBusqueda;
        Buscar.tipoBusqueda = combo;
        Buscar.consultaBuscar(); 
    }//GEN-LAST:event_buscar_botActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar_bot;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel nomPop1;
    public static javax.swing.JLabel nomPop2;
    public static javax.swing.JLabel nomPop3;
    public static javax.swing.JLabel nomRecom1;
    public static javax.swing.JLabel nomRecom2;
    public static javax.swing.JLabel nomRecom3;
    public static javax.swing.JLabel pop1;
    public static javax.swing.JLabel pop2;
    public static javax.swing.JLabel pop3;
    public static javax.swing.JLabel recom1;
    public static javax.swing.JLabel recom2;
    public static javax.swing.JLabel recom3;
    private javax.swing.JTextField text_buscar;
    public static javax.swing.JLabel tuNombre;
    // End of variables declaration//GEN-END:variables
}
